export const OBTER_PROJETOS = "OBTER PROJETOS";
export const CADASTRAR_PROJETO = "CADASTRAR PROJETO";
export const ALTERAR_PROJETO = "ALTERAR PROJETO";
export const REMOVER_PROJETO = "REMOVER PROJETO";

export const OBTER_TAREFAS = "OBTER TAREFAS";
export const CADASTRAR_TAREFA = "CADASTRAR TAREFA";
export const ALTERAR_TAREFA = "ALTERAR TAREFA";